name: Build Component

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile for master
        if: github.ref == 'refs/heads/master'
        uses: esphome/build-action@v4.0.1
        with:
          yaml_file: .github/example-project-master.yaml

      - name: Compile for dev
        if: github.ref != 'refs/heads/master'
        uses: esphome/build-action@v4.0.1
        with:
          yaml_file: .github/example-project-dev.yaml